export const NAME_ACTIONS={
    SHOPPING_CART_ACTIONS:{
        INCREASE_QUANTITY : 'INCREASE_QUANTITY',
        GET_ALL_PRODUCT : 'GET_ALL_PRODUCT',
        GET_NUMBER_CART : 'GET_NUMBER_CART',
        ADD_CART : 'ADD_CART' ,
        UPDATE_CART : 'UPDATE_CART',
        DELETE_CART : 'DELETE_CART',
        GET_TOTAL_BILL : 'GET_TOTAL_BILL',
        SHOPPING_CART_ACTIONS_SUCCESS : 'SHOPPING_CART_ACTIONS_SUCCESS',
        SHOPPING_CART_ACTIONS_FAIL : 'SHOPPING_CART_ACTIONS_FAIL',
    }
}
