export const NAME_ACTIONS={
    SHOPPING_CART_ACTIONS:{
        GET_ALL_SCREEN : 'GET_ALL_SCREEN',
        GET_ALL_SUCCESS : 'GET_ALL_SUCCESS',
        GET_ALL_FAIL : 'GET_ALL_FAIL',
        ADD_SCREEN : 'ADD_SCREEN' ,
        ADD_SUCCESS : 'ADD_SUCCESS' ,
        ADD_FAIL : 'ADD_FAIL' ,
        GET_NUMBER_CART : 'GET_NUMBER_CART',
       
        UPDATE_CART : 'UPDATE_CART',
        DELETE_CART : 'DELETE_CART',
        GET_TOTAL_BILL : 'GET_TOTAL_BILL',
        SHOPPING_CART_ACTIONS_SUCCESS : 'SHOPPING_CART_ACTIONS_SUCCESS',
        SHOPPING_CART_ACTIONS_FAIL : 'SHOPPING_CART_ACTIONS_FAIL',
    }
}
