export const NAME_EPICS={
    SHOPPING_CART_EPICS :{
        GET_ALL_EPICS_SCREEN : 'GET_ALL_EPICS_SCREEN',
        GET_ALL_EPICS_SUCCESS : 'GET_ALL_EPICS_SUCCESS',
        GET_ALL_EPICS_FAIL : 'GET_ALL_EPICS_FAIL',
        ADD_EPICS_SCREEN : 'ADD_EPICS_SCREEN',
        ADD_EPICS_SUCCESS : 'ADD_EPICS_SUCCESS',
        ADD_EPICS_FAIL : 'ADD_EPICS_FAIL',
        SHOPPING_CART_EPICS_DELETE : 'SHOPPING_CART_EPICS_DELETE',
        REMOVE_ITEM_EPICS_SCREEN:'REMOVE_ITEM_EPICS_SCREEN',
        REMOVE_ITEM_EPIC_SUCCESS:'REMOVE_ITEM_EPIC_SUCCESS',
        REMOVE_ITEM_EPIC_FAIL:'REMOVE_ITEM_EPIC_FAIL',
        RESET_STATUS:'RESET_STATUS'
    }
}