export const NAME_EPICS={
    SHOPPING_CART_EPICS :{
        SHOPPING_CART_EPICS_SCREEN : 'SHOPPING_CART_EPICS_SCREEN',
        SHOPPING_CART_EPICS_SUCCESS : 'SHOPPING_CART_EPICS_SUCCESS',
        SHOPPING_CART_EPICS_FAIL : 'SHOPPING_CART_EPICS_FAIL',
        SHOPPING_CART_EPICS_ADD : 'SHOPPING_CART_EPICS_ADD',
        SHOPPING_CART_EPICS_DELETE : 'SHOPPING_CART_EPICS_DELETE',
    }
}