export const NAME_EPICS = {
  GET_LIST_MESSAGE :{
    GET_LIST_MESSAGE_SCREEN  : 'GET_LIST_MESSAGE_SCREEN',
    GET_LIST_MESSAGE_SUCCESS : 'GET_LIST_MESSAGE_SUCCESS',
    GET_LIST_MESSAGE_FAIL : 'GET_LIST_MESSAGE_FAIL',
    SEND_MESSAGE_SUCCESS : 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAIL :'SEND_MESSAGE_FAIL',
  },
}