export const NAME_ACTIONS = {
  EDIT_PROFILE : {
    EDIT_PROFILE_ACTIONS : 'EDIT_PROFILE_ACTIONS',
    EDIT_PROFILE_SUCCESS : 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAIL : 'EDIT_PROFILE_FAIL'
  }
}