export const NAME_ACTIONS = {
  PUSH_NOTIFICATIONS_ACTION : {
    PUSH_NOTIFICATIONS_ACTION : 'PUSH_NOTIFICATIONS_ACTION',
    PUSH_NOTIFICATIONS_ACTION_SUCCESS : 'PUSH_NOTIFICATIONS_ACTION_SUCCESS',
    PUSH_NOTIFICATIONS_ACTION_FAIL : 'PUSH_NOTIFICATIONS_ACTION_FAIL',
    PUSH_NOTIFICATIONS_ACTION_RESET : 'PUSH_NOTIFICATIONS_ACTION_RESET',
  }
}