export const NAME_ACTIONS = {
    GET_REVIEWS_ITEMS : {
      GET_REVIEWS_ITEMS_ACTION : 'GET_REVIEWS_ITEMS_ACTION',
      GET_REVIEWS_ITEMS_SUCCESS : 'GET_REVIEWS_ITEMS_SUCCESS',
      GET_REVIEWS_ITEMS_FAIL : 'GET_REVIEWS_ITEMS_FAIL'
    },
    ADD_REVIEWS_ITEM : {
      ADD_REVIEWS_ITEM_ACTION : 'ADD_REVIEWS_ITEM_ACTION',
      ADD_REVIEWS_ITEM_SUCCESS : 'ADD_REVIEWS_ITEM_SUCCESS',
      ADD_REVIEWS_ITEM_FAIL : 'ADD_REVIEWS_ITEM_FAIL'
    },
    DELETE_REVIEWS_ITEM : {
      DELETE_REVIEWS_ITEM_ACTION : 'DELETE_REVIEWS_ITEM_ACTION',
      DELETE_REVIEWS_ITEM_SUCCESS : 'DELETE_REVIEWS_ITEM_SUCCESS',
      DELETE_REVIEWS_ITEM_FAIL : 'DELETE_REVIEWS_ITEM_FAIL'
    }
  }
