export const NAME_ACTIONS = {
    GET_REVIEWS_ITEMS : {
      GET_REVIEWS_ITEMS_ACTION : 'GET_REVIEWS_ITEMS_ACTION',
      GET_REVIEWS_ITEMS_SUCCESS : 'GET_REVIEWS_ITEMS_SUCCESS',
      GET_REVIEWS_ITEMS_FAIL : 'GET_REVIEWS_ITEMS_FAIL'
    }
  }