export const  NAME_ACTIONS={
    BILL_SCREEN:{
        GET_ALL_SCREEN:'GET_ALL_SCREEN',
        GET_ALL_SUCCESS:'GET_ALL_SUCCESS',
        GET_ALL_FAIL:'GET_ALL_FAIL',
    },
    CHECKOUT_SCREEN:{
        CHECKOUT_SCREEN:'CHECKOUT_SCREEN',
        CHECKOUT_SUCCESS:'CHECKOUT_SUCCESS',
        CHECKOUT_FAIL:'CHECKOUT_FAIL',
       
    }
}