export const NAME_EPICS = {
  PUSH_NOTIFICATIONS_EPICS :{
    PUSH_NOTIFICATIONS_EPICS_SCREEN : 'PUSH_NOTIFICATIONS_EPICS_SCREEN',
    PUSH_NOTIFICATIONS_EPICS_SUCCESS : 'PUSH_NOTIFICATIONS_EPICS_SUCCESS',
    PUSH_NOTIFICATIONS_EPICS_FAIL : 'PUSH_NOTIFICATIONS_EPICS_FAIL',
    PUSH_NOTIFICATIONS_EPICS_RESET : 'PUSH_NOTIFICATIONS_EPICS_RESET',
  }
}