export const NAME_ACTIONS = {
    GET_ARRIVAL_ITEM : {
      GET_ARRIVAL_ITEM_ACTION : 'GET_ARRIVAL_ITEM_ACTION',
      GET_ARRIVAL_ITEM_SUCCESS : 'GET_ARRIVAL_ITEM_SUCCESS',
      GET_ARRIVAL_ITEM_FAIL : 'GET_ARRIVAL_ITEM_FAIL'
    }
  }