export const NAME_ACTIONS = {
    GET_ARRIVAL_ITEM : {
      GET_ARRIVAL_ITEM_ACTION : 'GET_ARRIVAL_ITEM_ACTION',
      GET_ARRIVAL_ITEM_SUCCESS : 'GET_ARRIVAL_ITEM_SUCCESS',
      GET_ARRIVAL_ITEM_FAIL : 'GET_ARRIVAL_ITEM_FAIL'
    },
    EDIT_PRODUCT:{
      EDIT_PRODUCT_ACTIONS : 'EDIT_PRODUCT_ACTIONS',
      EDIT_PRODUCT_SUCCESS : 'EDIT_PRODUCT_SUCCESS',
      EDIT_PRODUCT_FAIL : 'EDIT_PRODUCT_FAIL'
    },
    ADD_PRODUCT:{
      ADD_PRODUCT_ACTIONS : 'ADD_PRODUCT_ACTIONS',
      ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
      ADD_PRODUCT_FAIL : 'ADD_PRODUCT_FAIL'
    }
  }