export const NAME_ACTIONS = {
  PUBLISHER_ÌNFO_SCREEN : {
    PUBLISHER_ÌNFO_SCREEN : 'PUBLISHER_ÌNFO_SCREEN',
    PUBLISHER_ÌNFO_SUCCESS : 'PUBLISHER_ÌNFO_SUCCESS',
    PUBLISHER_ÌNFO_FAIL : 'PUBLISHER_ÌNFO_FAIL',
  }
}