export const NAME_ACTIONS = {
  LOGIN_SCREEN : {
    LOGIN_SCREEN : 'LOGIN_SCREEN',
    LOGIN_ACTION_SUCCESS : 'LOGIN_ACTION_SUCCESS',
    LOGIN_ACTION_FAIL : 'LOGIN_ACTION_FAIL',
    EDIT_PROFILE_ACTIONS : 'EDIT_PROFILE_ACTIONS',
    EDIT_PROFILE_SUCCESS : 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAIL : 'EDIT_PROFILE_FAIL'
  }
}