export const NAME_EPICS = {
  GET_ITEMS_FOR_USER_EPICS : {
    GET_ITEMS_FOR_USER_EPICS_SCREEN : 'GET_ITEMS_FOR_USER_EPICS_SCREEN',
    GET_ITEMS_FOR_USER_EPICS_SUCCESS : 'GET_ITEMS_FOR_USER_EPICS_SUCCESS',
    GET_ITEMS_FOR_USER_EPICS_FAIL : 'GET_ITEMS_FOR_USER_EPICS_FAIL',
  }
}