export const NAME_EPICS = {
    ADRESS_EPICS : {
      GET_EPICS_SCREEN : 'GET_EPICS_SCREEN',
      GET_EPICS_SUCCESS : 'GET_EPICS_SUCCESS',
      GET_EPICS_FAIL : 'GET_EPICS_FAIL',
      GET_LIST_EPICS_ADRESS : 'GET_LIST_EPICS_ADRESS',
      ADD_EPICS_SCREEN : 'ADD_EPICS_SCREEN',
      ADD_EPICS_SUCCESS : 'ADD_EPICS_SUCCESS',
      ADD_EPICS_FAIL : 'ADD_EPICS_FAIL',
      SET_DEFAULT : 'SET_DEFAULT',
      REMOVE_EPICS_ADRESS : 'REMOVE_EPICS_ADRESS',
      UPDATE_EPICS_ADRESS : 'UPDATE_EPICS_ADRESS',
      ADRESS_EPICS_SUCCESS : 'ADRESS_EPICS_SUCCESS',
      ADRESS_EPICS_FAIL : 'ADRESS_EPICS_FAIL',
    }
  }