export const NAME_EPICS = {
    GET_LIST_REVIEWS_EPICS :{
      GET_LIST_REVIEWS_EPICS_SCREEN : 'GET_LIST_REVIEWS_EPICS_SCREEN',
      GET_LIST_REVIEWS_EPICS_SUCCESS : 'GET_LIST_REVIEWS_EPICS_SUCCESS',
      GET_LIST_REVIEWS_EPICS_FAIL : 'GET_LIST_REVIEWS_EPICS_FAIL'
    }
  }