export const NAME_EPICS = {
  EDIT_PROFILE_SCREEN : {
    EDIT_PROFILE_SCREEN : 'EDIT_PROFILE_SCREEN',
    EDIT_PROFILE_SUCCESS : 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAIL : 'EDIT_PROFILE_FAIL'
  }
}