export const NAME_ACTIONS = {
  GET_ITEM_FOR_USER : {
    GET_ITEM_FOR_USER_ACTIONS : 'GET_ITEM_FOR_USER_ACTIONS',
    GET_ITEM_FOR_USER_SUCCESS : 'GET_ITEM_FOR_USER_SUCCESS',
    GET_ITEM_FOR_USER_FAIL : 'GET_ITEM_FOR_USER_FAIL'
  }
}