export const NAME_ACTIONS = {
    ADDRESS_ACTIONS : {
      GET_ACTION_SCREEN : 'GET_ACTION_SCREEN',
      GET_ACTION_SUCCESS : 'GET_ACTION_SUCCESS',
      GET_ACTION_FAIL : 'GET_ACTION_FAIL',
      ADD_ACTION_SCREEN : 'ADD_ACTION_SCREEN',
      ADD_ACTION_SUCCESS : 'ADD_ACTION_SUCCESS',
      ADD_ACTION_FAIL : 'ADD_ACTION_FAIL',
      GET_LIST_ADDRESS : 'GET_LIST_ADDRESS',
      SET_DEFAULT : 'SET_DEFAULT',
      REMOVE_ADDRESS : 'REMOVE_ADDRESS',
      UPDATE_ADDRESS : 'UPDATE_ADDRESS',
      ADDRESS_ACTION_SUCCESS:'ADDRESS_ACTION_SUCCESS',
      ADDRESS_ACTION_FAIL:'ADDRESS_ACTION_FAIL',

    },
    CHECKOUT_SCREEN:{
      GET_DEFAULT_SCREEN:'GET_DEFAULT_SCREEN',
      GET_DEFAULT_SUCCESS:'GET_DEFAULT_SUCCESS',
      GET_DEFAULT_FAIL:'GET_DEFAULT_FAIL'
    },
    ADD_ADDRESS_SCREEN:{
      CHANGE_STATUS_TO_FAIL_SCREEN:'CHANGE_STATUS_TO_FAIL_SCREEN',
      CHANGE_STATUS_TO_FAIL_SUCCESS:'CHANGE_STATUS_TO_FAIL_SUCCESS',
      CHANGE_STATUS_TO_FAIL_FAIL:'CHANGE_STATUS_TO_FAIL_FAIL',
    }
  }