export const NAME_ACTIONS = {
    ADRESS_ACTIONS : {
      GET_ACTION_SCREEN : 'GET_ACTION_SCREEN',
      GET_ACTION_SUCCESS : 'GET_ACTION_SUCCESS',
      GET_ACTION_FAIL : 'GET_ACTION_FAIL',
      ADD_ACTION_SCREEN : 'ADD_ACTION_SCREEN',
      ADD_ACTION_SUCCESS : 'ADD_ACTION_SUCCESS',
      ADD_ACTION_FAIL : 'ADD_ACTION_FAIL',
      GET_LIST_ADRESS : 'GET_LIST_ADRESS',
      SET_DEFAULT : 'SET_DEFAULT',
      REMOVE_ADRESS : 'REMOVE_ADRESS',
      UPDATE_ADRESS : 'UPDATE_ADRESS',
      ADRESS_ACTION_SUCCESS:'ADRESS_ACTION_SUCCESS',
      ADRESS_ACTION_FAIL:'ADRESS_ACTION_FAIL',

    }
  }