export const NAME_ACTIONS = {
    ADRESS_ACTIONS : {
      GET_ADRESS : 'GET_ADRESS',
      GET_LIST_ADRESS : 'GET_LIST_ADRESS',
      ADD_ADRESS : 'ADD_ADRESS',
      SET_DEFAULT : 'SET_DEFAULT',
      REMOVE_ADRESS : 'REMOVE_ADRESS',
      UPDATE_ADRESS : 'UPDATE_ADRESS',
      ADRESS_ACTION_SUCCESS:'ADRESS_ACTION_SUCCESS',
      ADRESS_ACTION_FAIL:'ADRESS_ACTION_FAIL',

    }
  }