export const NAME_EPICS = {
  LOGIN_EPICS_SCREEN : {
    LOGIN_EPICS_SCREEN : 'LOGIN_EPICS_SCREEN',
    LOGIN_EPICS_SUCCESS : 'LOGIN_EPICS_SUCCESS',
    LOGIN_EPICS_FAIL : 'LOGIN_EPICS_FAIL',
    EDIT_PROFILE_SCREEN : 'EDIT_PROFILE_SCREEN',
    EDIT_PROFILE_SUCCESS : 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAIL : 'EDIT_PROFILE_FAIL',
    LOGOUT_SCREEN  : 'LOGOUT_SCREEN',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
  }
}