export const NAME_ACTIONS = {
  GET_NEW_ARRIVALS_ITEMS : {
    GET_NEW_ARRIVALS_ITEMS_ACTION : 'GET_NEW_ARRIVALS_ITEMS_ACTION',
    GET_NEW_ARRIVALS_ITEMS_SUCCESS : 'GET_NEW_ARRIVALS_ITEMS_SUCCESS',
    GET_NEW_ARRIVALS_ITEMS_FAIL : 'GET_NEW_ARRIVALS_ITEMS_FAIL'
  }
}