export const NAME_EPICS = {
    ADDRESS_EPICS : {
      GET_EPICS_SCREEN : 'GET_EPICS_SCREEN',
      GET_EPICS_SUCCESS : 'GET_EPICS_SUCCESS',
      GET_EPICS_FAIL : 'GET_EPICS_FAIL',
      GET_LIST_EPICS_ADDRESS : 'GET_LIST_EPICS_ADDRESS',
      ADD_EPICS_SCREEN : 'ADD_EPICS_SCREEN',
      ADD_EPICS_SUCCESS : 'ADD_EPICS_SUCCESS',
      ADD_EPICS_FAIL : 'ADD_EPICS_FAIL',
      SET_DEFAULT : 'SET_DEFAULT',
      REMOVE_EPICS_ADDRESS : 'REMOVE_EPICS_ADDRESS',
      UPDATE_EPICS_ADDRESS : 'UPDATE_EPICS_ADDRESS',
      ADDRESS_EPICS_SUCCESS : 'ADDRESS_EPICS_SUCCESS',
      ADDRESS_EPICS_FAIL : 'ADDRESS_EPICS_FAIL',
    },
    CHECKOUT_EPICS_SCREEN:{
      GET_DEFAULT_EPIC_SCREEN:'GET_DEFAULT_EPIC_SCREEN',
      GET_DEFAULT_EPIC_SUCCESS:'GET_DEFAULT_EPIC_SUCCESS',
      GET_DEFAULT_EPIC_FAIL:'GET_DEFAULT_EPIC_FAIL',
    },
    ADD_ADDRESS_EPICS_SCREEN:{
      CHANGE_STATUS_EPIC_SCREEN:'CHANGE_STATUS_EPIC_SCREEN',
      CHANGE_STATUS_EPIC_SUCCESS:'CHANGE_STATUS_EPIC_SUCCESS',
      CHANGE_STATUS_EPIC_FAIL:'CHANGE_STATUS_EPIC_FAIL',
    }
  }