export const NAME_EPICS = {
  GET_PUBLISHER_INFO_EPICS :{
    GET_PUBLISHER_INFO_EPICS_SCREEN : 'GET_PUBLISHER_INFO_EPICS_SCREEN',
    GET_PUBLISHER_INFO_EPICS_SUCCESS : 'GET_PUBLISHER_INFO_EPICS_SUCCESS',
    GET_PUBLISHER_INFO_EPICS_FAIL : 'GET_PUBLISHER_INFO_EPICS_FAIL'
  }
}