export const NAME_EPICS = {
  GET_LIST_NEW_ARRIVALS_EPICS :{
    GET_LIST_NEW_ARRIVALS_EPICS_SCREEN : 'GET_LIST_NEW_ARRIVALS_EPICS_SCREEN',
    GET_LIST_NEW_ARRIVALS_EPICS_SUCCESS : 'GET_LIST_NEW_ARRIVALS_EPICS_SUCCESS',
    GET_LIST_NEW_ARRIVALS_EPICS_FAIL : 'GET_LIST_NEW_ARRIVALS_EPICS_FAIL'
  }
}