export const NAME_EPICS = {
    SIGNUP_EPICS_SCREEN:{
        SIGNUP_EPICS_SCREEN:'SIGNUP_EPICS_SCREEN',
        SIGNUP_EPICS_SUCCESS:'SIGNUP_EPICS_SUCCESS',
        SIGNUP_EPICS_FAIL:'SIGNUP_EPICS_FAIL'
    }
  }