export const NAME_ACTIONS = {
  MESSAGE_ACTION : {
    GET_LIST_MESSAGE_ACTION : 'MESSAGE_ACTION',
    GET_LIST_MESSAGE_SUCCESS : 'GET_LIST_MESSAGE_SUCCESS',
    GET_LIST_MESSAGE_FAIL : 'GET_LIST_MESSAGE_FAIL',
    SEND_MESSAGE_ACTION : 'SEND_MESSAGE_ACTION',
    SEND_MESSAGE_SUCCESS : 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAIL : 'SEND_MESSAGE_FAIL'
  }
}