export const NAME_EPICS = {
    GET_ARRIVAL_ITEM_EPICS :{
      GET_ARRIVAL_ITEM_EPICS_SCREEN : 'GET_ARRIVAL_ITEM_EPICS_SCREEN',
      GET_ARRIVAL_ITEM_EPICS_SUCCESS : 'GET_ARRIVAL_ITEM_EPICS_SUCCESS',
      GET_ARRIVAL_ITEM_EPICS_FAIL : 'GET_ARRIVAL_ITEM_EPICS_FAIL'
    },
    EDIT_PRODUCT_EPICS:{
      EDIT_PRODUCT_SCREEN : 'EDIT_PRODUCT_SCREEN',
      EDIT_PRODUCT_SUCCESS : 'EDIT_PRODUCT_SUCCESS',
      EDIT_PRODUCT_FAIL : 'EDIT_PRODUCT_FAIL'
    },
    ADD_PRODUCT_EPICS:{
      ADD_PRODUCT_SCREEN : 'ADD_PRODUCT_SCREEN',
      ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
      ADD_PRODUCT_FAIL : 'ADD_PRODUCT_FAIL'
    },
    DELETE_PRODUCT_EPICS:{
      DELETE_PRODUCT_SCREEN : 'DELETE_PRODUCT_SCREEN',
      DELETE_PRODUCT_SUCCESS : 'DELETE_PRODUCT_SUCCESS',
      DELETE_PRODUCT_FAIL : 'DELETE_PRODUCT_FAIL'
    }
  }