export const NAME_EPICS = {
    GET_ARRIVAL_ITEM_EPICS :{
      GET_ARRIVAL_ITEM_EPICS_SCREEN : 'GET_ARRIVAL_ITEM_EPICS_SCREEN',
      GET_ARRIVAL_ITEM_EPICS_SUCCESS : 'GET_ARRIVAL_ITEM_EPICS_SUCCESS',
      GET_ARRIVAL_ITEM_EPICS_FAIL : 'GET_ARRIVAL_ITEM_EPICS_FAIL'
    }
  }