export const NAME_EPICS = {
    GET_ARRIVAL_ITEM_EPICS :{
      GET_ARRIVAL_ITEM_EPICS_SCREEN : 'GET_ARRIVAL_ITEM_EPICS_SCREEN',
      GET_ARRIVAL_ITEM_EPICS_SUCCESS : 'GET_ARRIVAL_ITEM_EPICS_SUCCESS',
      GET_ARRIVAL_ITEM_EPICS_FAIL : 'GET_ARRIVAL_ITEM_EPICS_FAIL'
    },
    EDIT_PRODUCT_EPICS:{
      EDIT_PRODUCT_SCREEN : 'EDIT_PRODUCT_SCREEN',
      EDIT_PRODUCT_SUCCESS : 'EDIT_PRODUCT_SUCCESS',
      EDIT_PRODUCT_FAIL : 'EDIT_PRODUCT_FAIL'
    }
  }